name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    name: Source Code Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Semgrep with comprehensive ruleset
        run: |
          echo "=== Running Semgrep with multiple rulesets ==="
          
          semgrep --config=p/java \
                  --config=p/security-audit \
                  --config=p/owasp-top-ten \
                  --config=p/secrets \
                  --config=r/java.spring.security \
                  --config=r/java.lang.security \
                  --sarif --output=semgrep-comprehensive.sarif .
          
          echo "=== Semgrep Results Summary ==="
          if [ -f "semgrep-comprehensive.sarif" ]; then
            ISSUE_COUNT=$(cat semgrep-comprehensive.sarif | jq '.runs[0].results | length' 2>/dev/null || echo 0)
            echo "Total issues found: $ISSUE_COUNT"
            
            echo "=== Vulnerability types found ==="
            cat semgrep-comprehensive.sarif | jq -r '.runs[0].results[].ruleId' 2>/dev/null | sort | uniq -c
          fi
        continue-on-error: true
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-comprehensive.sarif
          category: source-code
        if: always()

  dependencies-analysis:
    runs-on: ubuntu-latest
    name: Dependencies Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run OWASP Dependency Check
        run: |
          echo "=== Running OWASP Dependency Check ==="
          wget -O dependency-check.zip "https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.3/dependency-check-8.4.3-release.zip"
          unzip dependency-check.zip
          
          ./dependency-check/bin/dependency-check.sh \
            --project "booking-epita" \
            --scan . \
            --format "JSON" \
            --format "SARIF" \
            --out . \
            --enableExperimental \
            --enableRetired \
            --failOnCVSS 0
        continue-on-error: true
        
      - name: Upload Dependency Check Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dependency-check-report.sarif
          category: dependencies
        if: always()
