name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 2h du matin UTC
  workflow_dispatch:      # Permet le déclenchement manuel

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    name: Dependencies Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          scan-args: |-
            --output=sarif
            --format=sarif
            .
        continue-on-error: true
            
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: dependencies
        if: always()

  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    name: Source Code Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Semgrep
        run: |
          semgrep --config=p/java --sarif --output=semgrep.sarif .
        continue-on-error: true
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: source-code
        if: always()
