name: Pull Request Security Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    name: Source Code Analysis (Differential)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Semgrep (Differential)
        run: |
          echo "Running Semgrep differential analysis..."
          semgrep --config=p/java \
                  --baseline-commit=${{ github.event.pull_request.base.sha }} \
                  --json --output=semgrep-diff.json . || true
                  
          if [ -f "semgrep-diff.json" ]; then
            echo "=== Semgrep Results ==="
            cat semgrep-diff.json | jq '.' || echo "No valid JSON output"
            NEW_ISSUES=$(cat semgrep-diff.json | jq '.results | length' 2>/dev/null || echo 0)
            echo "Found $NEW_ISSUES new security issues in this PR"
          fi
        continue-on-error: true
                  
      - name: Upload Security Results
        uses: actions/upload-artifact@v4
        with:
          name: source-code-scan-results
          path: semgrep-diff.json
        if: always()

  dependencies-placeholder:
    runs-on: ubuntu-latest
    name: Dependencies Analysis (Differential)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Placeholder for dependency scanning
        run: |
          echo "✅ Dependency scanning job executed successfully"
          echo "Note: OSV Scanner temporarily disabled due to configuration issues"
